layout_spectrum: 0.7849463
color:
  saturation: 0
  brandStrength: 0.04659498
  lightness: 0.8978494
  rhythmicContrast: 1
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
typography_spectrum: 0
name: Meaning
